export interface Lesson {
  id: string;
  title: string;
  youtubeId: string;
  duration: string;
  description: string;
  order: number;
}

export interface Course {
  id: string;
  title: string;
  category: string;
  categoryColor: string;
  description: string;
  level: '初級' | '中級' | '上級';
  totalLessons: number;
  totalDuration: string;
  icon: string;
  lessons: Lesson[];
  examInfo: string;
  prerequisites: string;
}

export const COURSES: Course[] = [
  {
    id: 'forklift',
    title: 'フォークリフト運転技能講習',
    category: '荷役機械',
    categoryColor: 'bg-orange-500',
    description: 'フォークリフトの構造、操作方法、荷役作業の安全に関する法令を学習します。最大荷重1トン以上のフォークリフト運転に必要な資格です。',
    level: '初級',
    totalLessons: 8,
    totalDuration: '約35時間',
    icon: '🏗️',
    examInfo: '学科試験＋実技試験｜合格基準：各科目40点以上・合計60点以上',
    prerequisites: '特になし（満18歳以上）',
    lessons: [
      {
        id: 'forklift-01',
        title: 'フォークリフトの種類と用途',
        youtubeId: 'dMH0bHeiRNg',
        duration: '15:32',
        description: 'カウンターバランス式・リーチ式など各種フォークリフトの特徴と用途を解説。',
        order: 1,
      },
      {
        id: 'forklift-02',
        title: 'フォークリフトの主要構造と各部名称',
        youtubeId: 'BFaRD6AIJtk',
        duration: '22:15',
        description: 'マスト・フォーク・バックレスト・カウンターウェイトなど主要部品を学習。',
        order: 2,
      },
      {
        id: 'forklift-03',
        title: '荷役装置の操作方法',
        youtubeId: 'HzeK7g8cX0s',
        duration: '18:40',
        description: 'ティルトレバー・リフトレバーの操作手順と安全確認ポイント。',
        order: 3,
      },
      {
        id: 'forklift-04',
        title: '走行の基本操作',
        youtubeId: 'C1ogWPCfJY8',
        duration: '20:10',
        description: '発進・停止・旋回・後退の基本操作と注意点を動画で確認。',
        order: 4,
      },
      {
        id: 'forklift-05',
        title: 'パレット積み下ろし作業の手順',
        youtubeId: 'z3rVJVJa1Mg',
        duration: '16:55',
        description: 'パレットへの差し込み・持ち上げ・移動・積み下ろしの正しい手順。',
        order: 5,
      },
      {
        id: 'forklift-06',
        title: '日常点検と整備',
        youtubeId: 'TqX3r-sMEsM',
        duration: '12:30',
        description: '作業前点検チェックリストと主要箇所の点検方法。',
        order: 6,
      },
      {
        id: 'forklift-07',
        title: '労働安全衛生法・関係法令',
        youtubeId: 'r6CoEpyGzgw',
        duration: '25:00',
        description: 'フォークリフト作業に関わる法令・規則・安全基準を解説。',
        order: 7,
      },
      {
        id: 'forklift-08',
        title: '災害事例と安全対策',
        youtubeId: '4k9VFvSiOBk',
        duration: '19:45',
        description: '実際の労働災害事例から学ぶ安全作業のポイント。',
        order: 8,
      },
    ],
  },
  {
    id: 'tamakake',
    title: '玉掛け技能講習',
    category: 'クレーン関係',
    categoryColor: 'bg-blue-600',
    description: 'クレーン等の玉掛け作業（吊り荷のワイヤーロープかけ外し）に必要な技能講習です。1トン以上の荷を扱うすべての現場で必要とされます。',
    level: '初級',
    totalLessons: 9,
    totalDuration: '約19時間',
    icon: '⚙️',
    examInfo: '学科試験＋実技試験｜合格基準：学科60点以上・実技60点以上',
    prerequisites: '特になし（満18歳以上）',
    lessons: [
      {
        id: 'tamakake-01',
        title: 'クレーン等の基礎知識',
        youtubeId: 'gZYzAVSHjmw',
        duration: '20:15',
        description: '天井クレーン・橋形クレーン・移動式クレーンの種類と構造。',
        order: 1,
      },
      {
        id: 'tamakake-02',
        title: 'ワイヤーロープの種類と選定',
        youtubeId: 'IKPkMZk4A9w',
        duration: '18:30',
        description: '玉掛け用ワイヤーロープの構造・特徴・使用前点検と廃棄基準。',
        order: 2,
      },
      {
        id: 'tamakake-03',
        title: '吊り具（スリング）の種類と使い方',
        youtubeId: 'J0mGLDMmF3U',
        duration: '22:00',
        description: 'チェーンスリング・ベルトスリング・シャックルの選定と使用方法。',
        order: 3,
      },
      {
        id: 'tamakake-04',
        title: '荷の質量の計算方法',
        youtubeId: 'XbKmRRkCFzA',
        duration: '25:10',
        description: '各種材料の比重と質量計算・定格荷重の確認方法。',
        order: 4,
      },
      {
        id: 'tamakake-05',
        title: '玉掛けの基本作業手順',
        youtubeId: 'HuEBP5BBHD4',
        duration: '28:00',
        description: '目掛け・あや掛け・絞り掛けの正しい掛け方と確認手順。',
        order: 5,
      },
      {
        id: 'tamakake-06',
        title: '多点吊りの方法',
        youtubeId: 'mA3JFYdPqsU',
        duration: '20:45',
        description: '2点吊り・4点吊りの手順とバランス調整のポイント。',
        order: 6,
      },
      {
        id: 'tamakake-07',
        title: '合図の方法',
        youtubeId: 'bV7hbv4JAJY',
        duration: '15:20',
        description: 'クレーンオペレーターへの手合図・旗合図・無線合図の標準的な方法。',
        order: 7,
      },
      {
        id: 'tamakake-08',
        title: '安全作業のポイント',
        youtubeId: 'K2XwAi8ejXE',
        duration: '18:00',
        description: '吊り荷下への立入禁止・風の影響・地盤確認など安全対策。',
        order: 8,
      },
      {
        id: 'tamakake-09',
        title: '労働安全衛生法・クレーン則',
        youtubeId: 'r6CoEpyGzgw',
        duration: '22:30',
        description: '玉掛け作業に関わる法令・資格要件・定期自主検査。',
        order: 9,
      },
    ],
  },
  {
    id: 'mobile-crane',
    title: '移動式クレーン運転士',
    category: 'クレーン関係',
    categoryColor: 'bg-blue-600',
    description: '吊り上げ荷重5トン以上の移動式クレーンを運転するための国家資格。大型建設現場・港湾・プラント工事に欠かせない上位資格です。',
    level: '上級',
    totalLessons: 10,
    totalDuration: '約4か月（学科＋実技）',
    icon: '🏚️',
    examInfo: '学科試験（安全・法令・力学・電気）＋実技試験（運転）',
    prerequisites: '小型移動式クレーン技能講習修了者など',
    lessons: [
      {
        id: 'mc-01',
        title: '移動式クレーンの種類と構造',
        youtubeId: 'gZYzAVSHjmw',
        duration: '30:20',
        description: 'ラフタークレーン・オールテレーン・カーゴクレーンの構造と特徴。',
        order: 1,
      },
      {
        id: 'mc-02',
        title: '原動機（エンジン）の知識',
        youtubeId: 'vFqAuiPjM0A',
        duration: '25:15',
        description: 'ディーゼルエンジンの構造・点検・トラブルシューティング。',
        order: 2,
      },
      {
        id: 'mc-03',
        title: '電気・油圧系統の基礎',
        youtubeId: 'kHmDgTFEYgY',
        duration: '28:00',
        description: '電気系統の基礎知識と油圧回路の仕組み・点検ポイント。',
        order: 3,
      },
      {
        id: 'mc-04',
        title: 'アウトリガーの張り出し作業',
        youtubeId: 'z3rVJVJa1Mg',
        duration: '22:40',
        description: '作業前準備・アウトリガー設置・地耐力確認の手順。',
        order: 4,
      },
      {
        id: 'mc-05',
        title: 'ブームの操作基礎',
        youtubeId: 'HzeK7g8cX0s',
        duration: '26:30',
        description: 'ブーム起伏・旋回・伸縮の操作手順と複合操作の注意点。',
        order: 5,
      },
      {
        id: 'mc-06',
        title: 'つり上げ荷重と定格荷重の計算',
        youtubeId: 'XbKmRRkCFzA',
        duration: '20:00',
        description: '性能曲線の読み方・作業半径と定格荷重の関係を計算で理解。',
        order: 6,
      },
      {
        id: 'mc-07',
        title: '力学の基礎（モーメント・安定性）',
        youtubeId: 'C1ogWPCfJY8',
        duration: '35:00',
        description: '重心・モーメント・転倒防止の原則を数式と図解で学習。',
        order: 7,
      },
      {
        id: 'mc-08',
        title: '強風・悪天候時の対応',
        youtubeId: 'mA3JFYdPqsU',
        duration: '18:15',
        description: '風速規制・台風対策・走行注意事項と緊急停止手順。',
        order: 8,
      },
      {
        id: 'mc-09',
        title: 'クレーン則・関係法令',
        youtubeId: 'r6CoEpyGzgw',
        duration: '28:00',
        description: '資格要件・定期検査・作業計画作成義務など法令全般。',
        order: 9,
      },
      {
        id: 'mc-10',
        title: '実技試験対策・模擬演習',
        youtubeId: '4k9VFvSiOBk',
        duration: '32:00',
        description: '実技試験の採点基準と合格のためのポイント解説。',
        order: 10,
      },
    ],
  },
  {
    id: 'construction-vehicle',
    title: '車両系建設機械（整地・運搬・掘削）',
    category: '建設機械',
    categoryColor: 'bg-yellow-500',
    description: 'ブルドーザー・パワーショベル・モーターグレーダーなど整地・掘削用建設機械の運転に必要な技能講習です。土木工事の基本資格として幅広く求められます。',
    level: '初級',
    totalLessons: 9,
    totalDuration: '約38時間',
    icon: '🚜',
    examInfo: '学科試験＋実技試験｜合格基準：各科目40点以上・合計60点以上',
    prerequisites: '特になし（満18歳以上）',
    lessons: [
      {
        id: 'cv-01',
        title: '車両系建設機械の種類と用途',
        youtubeId: 'BFaRD6AIJtk',
        duration: '25:00',
        description: 'ブルドーザー・ショベル・グレーダーなど機種ごとの特徴と用途。',
        order: 1,
      },
      {
        id: 'cv-02',
        title: 'エンジン（原動機）の構造と整備',
        youtubeId: 'vFqAuiPjM0A',
        duration: '30:15',
        description: 'ディーゼルエンジンの各部構造・冷却系・燃料系の仕組み。',
        order: 2,
      },
      {
        id: 'cv-03',
        title: '走行装置・操縦装置',
        youtubeId: 'kHmDgTFEYgY',
        duration: '22:30',
        description: 'クローラ式・ホイール式の走行装置と各操作レバーの機能。',
        order: 3,
      },
      {
        id: 'cv-04',
        title: '油圧装置の基礎',
        youtubeId: 'z3rVJVJa1Mg',
        duration: '20:00',
        description: '油圧ポンプ・バルブ・シリンダーの構造と動作原理。',
        order: 4,
      },
      {
        id: 'cv-05',
        title: '作業装置の操作方法',
        youtubeId: 'HzeK7g8cX0s',
        duration: '28:00',
        description: 'ブレード・バケット・アームの操作手順と複合操作の注意点。',
        order: 5,
      },
      {
        id: 'cv-06',
        title: '走行の基本操作と注意点',
        youtubeId: 'C1ogWPCfJY8',
        duration: '24:15',
        description: '傾斜地走行・軟弱地盤・狭隘路での安全な走行方法。',
        order: 6,
      },
      {
        id: 'cv-07',
        title: '掘削・積み込み作業の手順',
        youtubeId: 'dMH0bHeiRNg',
        duration: '26:00',
        description: '掘削・すくい・旋回・積み込みの効率的かつ安全な作業手順。',
        order: 7,
      },
      {
        id: 'cv-08',
        title: '日常点検と定期整備',
        youtubeId: 'TqX3r-sMEsM',
        duration: '18:30',
        description: '作業前・作業後点検の手順とチェックポイント一覧。',
        order: 8,
      },
      {
        id: 'cv-09',
        title: '安全作業と関係法令',
        youtubeId: 'r6CoEpyGzgw',
        duration: '22:00',
        description: '誘導者の配置・立入禁止・転落防止対策と労働安全衛生法。',
        order: 9,
      },
    ],
  },
  {
    id: 'aerial-work',
    title: '高所作業車運転技能講習',
    category: '高所作業',
    categoryColor: 'bg-green-600',
    description: '作業床の高さが10m以上の高所作業車の運転に必要な技能講習。電気工事・通信工事・建設工事など高所での作業現場で広く使用されます。',
    level: '初級',
    totalLessons: 7,
    totalDuration: '約17時間',
    icon: '🔧',
    examInfo: '学科試験＋実技試験｜合格基準：各科目40点以上・合計60点以上',
    prerequisites: '特になし（満18歳以上）',
    lessons: [
      {
        id: 'aw-01',
        title: '高所作業車の種類と構造',
        youtubeId: 'BFaRD6AIJtk',
        duration: '20:00',
        description: 'ブーム式・シザース式・垂直昇降式の種類と各部名称。',
        order: 1,
      },
      {
        id: 'aw-02',
        title: '走行・作業装置の操作',
        youtubeId: 'C1ogWPCfJY8',
        duration: '22:30',
        description: '地上操作と上部バスケット内操作の手順と注意事項。',
        order: 2,
      },
      {
        id: 'aw-03',
        title: 'アウトリガー設置と転倒防止',
        youtubeId: 'z3rVJVJa1Mg',
        duration: '15:45',
        description: 'アウトリガー設置手順・地耐力確認・傾斜地での対応。',
        order: 3,
      },
      {
        id: 'aw-04',
        title: '作業前点検と整備',
        youtubeId: 'TqX3r-sMEsM',
        duration: '14:00',
        description: '安全装置・作業床・ブームの点検と整備方法。',
        order: 4,
      },
      {
        id: 'aw-05',
        title: '墜落・転落防止対策',
        youtubeId: 'K2XwAi8ejXE',
        duration: '18:00',
        description: '安全帯の使用方法・バスケット内での安全確保・立入禁止区域の設定。',
        order: 5,
      },
      {
        id: 'aw-06',
        title: '電線・障害物への接近注意',
        youtubeId: 'mA3JFYdPqsU',
        duration: '12:30',
        description: '電線接触事故の防止・安全離隔距離・風速規制。',
        order: 6,
      },
      {
        id: 'aw-07',
        title: '関係法令と作業計画',
        youtubeId: 'r6CoEpyGzgw',
        duration: '16:00',
        description: '高所作業車作業に関わる法令・資格要件・作業計画書の作成。',
        order: 7,
      },
    ],
  },
  {
    id: 'arc-welding',
    title: 'アーク溶接等特別教育',
    category: '溶接',
    categoryColor: 'bg-red-600',
    description: 'アーク溶接機を使用した溶接・溶断作業に必要な特別教育。製造業・建設業・修理業など幅広い現場で必要とされます。',
    level: '初級',
    totalLessons: 6,
    totalDuration: '約11時間',
    icon: '⚡',
    examInfo: '学科教育＋実技教育（修了試験あり）',
    prerequisites: '特になし（満18歳以上）',
    lessons: [
      {
        id: 'arc-01',
        title: 'アーク溶接の原理と種類',
        youtubeId: 'HuEBP5BBHD4',
        duration: '20:00',
        description: '被覆アーク溶接・MIG/MAG溶接・TIG溶接の原理と特徴。',
        order: 1,
      },
      {
        id: 'arc-02',
        title: '溶接機器・材料の取り扱い',
        youtubeId: 'J0mGLDMmF3U',
        duration: '18:30',
        description: '溶接機の構造・電流設定・溶接棒の種類と選定方法。',
        order: 2,
      },
      {
        id: 'arc-03',
        title: '基本的な溶接作業手順',
        youtubeId: 'IKPkMZk4A9w',
        duration: '25:00',
        description: 'アーク発生・運棒・ビード作成の基本手順と留意点。',
        order: 3,
      },
      {
        id: 'arc-04',
        title: '感電防止対策',
        youtubeId: 'K2XwAi8ejXE',
        duration: '15:00',
        description: '感電の原因・防護具の使用・安全作業のための注意事項。',
        order: 4,
      },
      {
        id: 'arc-05',
        title: '溶接ヒュームと有害光線の防護',
        youtubeId: 'bV7hbv4JAJY',
        duration: '14:00',
        description: '溶接ヒュームの健康障害・換気方法・遮光フィルターの選定。',
        order: 5,
      },
      {
        id: 'arc-06',
        title: '火災・爆発防止と関係法令',
        youtubeId: 'r6CoEpyGzgw',
        duration: '16:30',
        description: '引火性物質の取り扱い・消火器設置・特別教育に関する法令。',
        order: 6,
      },
    ],
  },
  {
    id: 'scaffold',
    title: '足場の組立て等作業主任者',
    category: '足場・架設',
    categoryColor: 'bg-purple-600',
    description: '足場（つり足場・張り出し足場・高さ5m以上）の組立て・解体または変更の作業において主任者として作業を指揮・監督する資格です。',
    level: '中級',
    totalLessons: 8,
    totalDuration: '約14時間',
    icon: '🏗️',
    examInfo: '学科試験｜合格基準：各科目40点以上・合計60点以上',
    prerequisites: '足場の組立て等に関する実務経験3年以上',
    lessons: [
      {
        id: 'scaf-01',
        title: '足場の種類と特徴',
        youtubeId: 'gZYzAVSHjmw',
        duration: '20:00',
        description: 'わく組足場・単管足場・くさび緊結式足場・吊り足場の種類と用途。',
        order: 1,
      },
      {
        id: 'scaf-02',
        title: '足場の構造基準',
        youtubeId: 'IKPkMZk4A9w',
        duration: '25:00',
        description: '手すり・中さん・幅木・床材の設置基準と強度要件。',
        order: 2,
      },
      {
        id: 'scaf-03',
        title: '組立て・解体の作業手順',
        youtubeId: 'J0mGLDMmF3U',
        duration: '28:00',
        description: '組立て計画・部材確認・組立て順序・解体手順の基本。',
        order: 3,
      },
      {
        id: 'scaf-04',
        title: '墜落防止のための安全対策',
        youtubeId: 'K2XwAi8ejXE',
        duration: '18:30',
        description: '安全帯・ライフライン・開口部養生など墜落防止対策の全体像。',
        order: 4,
      },
      {
        id: 'scaf-05',
        title: '作業主任者の職務',
        youtubeId: 'bV7hbv4JAJY',
        duration: '15:00',
        description: '作業主任者の役割・責任・作業指揮の方法と作業計画書の作成。',
        order: 5,
      },
      {
        id: 'scaf-06',
        title: '風荷重・積雪荷重への対応',
        youtubeId: 'mA3JFYdPqsU',
        duration: '16:00',
        description: '強風・積雪時の点検・補強・使用禁止基準と気象条件への対応。',
        order: 6,
      },
      {
        id: 'scaf-07',
        title: '足場の点検方法',
        youtubeId: 'TqX3r-sMEsM',
        duration: '14:00',
        description: '定期点検・悪天候後の点検・部材損傷の確認方法とチェックリスト。',
        order: 7,
      },
      {
        id: 'scaf-08',
        title: '労働安全衛生規則・関係法令',
        youtubeId: 'r6CoEpyGzgw',
        duration: '20:00',
        description: '足場に関わる法令・作業主任者の選任義務・罰則規定。',
        order: 8,
      },
    ],
  },
  {
    id: 'small-crane',
    title: '小型移動式クレーン運転技能講習',
    category: 'クレーン関係',
    categoryColor: 'bg-blue-600',
    description: 'つり上げ荷重1トン以上5トン未満の小型移動式クレーンを運転するための技能講習。中型クレーン作業の入門資格として広く活用されます。',
    level: '初級',
    totalLessons: 7,
    totalDuration: '約13時間',
    icon: '🏚️',
    examInfo: '学科試験＋実技試験｜合格基準：各科目40点以上・合計60点以上',
    prerequisites: '特になし（満18歳以上）',
    lessons: [
      {
        id: 'sc-01',
        title: '小型移動式クレーンの種類と構造',
        youtubeId: 'gZYzAVSHjmw',
        duration: '20:00',
        description: 'トラック搭載型・ラフタークレーンの小型機種の構造と各部名称。',
        order: 1,
      },
      {
        id: 'sc-02',
        title: '原動機・電気の基礎',
        youtubeId: 'vFqAuiPjM0A',
        duration: '18:00',
        description: 'エンジン・電装系の基礎知識と点検ポイント。',
        order: 2,
      },
      {
        id: 'sc-03',
        title: 'アウトリガー設置手順',
        youtubeId: 'z3rVJVJa1Mg',
        duration: '16:00',
        description: 'アウトリガーの最大張り出し・地耐力確認・敷板の使用方法。',
        order: 3,
      },
      {
        id: 'sc-04',
        title: 'ブーム・フックの操作',
        youtubeId: 'HzeK7g8cX0s',
        duration: '22:00',
        description: '起伏・旋回・巻き上げ操作の手順と複合操作の注意点。',
        order: 4,
      },
      {
        id: 'sc-05',
        title: '定格荷重と作業半径',
        youtubeId: 'XbKmRRkCFzA',
        duration: '15:00',
        description: '性能曲線の読み方・安全荷重の確認と過負荷防止装置の機能。',
        order: 5,
      },
      {
        id: 'sc-06',
        title: '玉掛け用具との連携',
        youtubeId: 'IKPkMZk4A9w',
        duration: '12:00',
        description: 'ワイヤーロープ・スリングとの組み合わせ作業と合図の確認。',
        order: 6,
      },
      {
        id: 'sc-07',
        title: '安全作業と関係法令',
        youtubeId: 'r6CoEpyGzgw',
        duration: '18:00',
        description: '作業半径内立入禁止・強風対応・クレーン則の要点。',
        order: 7,
      },
    ],
  },
];

export function getCourseById(id: string): Course | undefined {
  return COURSES.find(c => c.id === id);
}

export function getLessonById(courseId: string, lessonId: string): { course: Course; lesson: Lesson } | undefined {
  const course = getCourseById(courseId);
  if (!course) return undefined;
  const lesson = course.lessons.find(l => l.id === lessonId);
  if (!lesson) return undefined;
  return { course, lesson };
}

export function getLessonByIdOnly(lessonId: string): { course: Course; lesson: Lesson } | undefined {
  for (const course of COURSES) {
    const lesson = course.lessons.find(l => l.id === lessonId);
    if (lesson) return { course, lesson };
  }
  return undefined;
}

export const CATEGORY_LIST = [...new Set(COURSES.map(c => c.category))];
